namespace: senhasegura
name: pam
version: 1.0.0
readme: README.md
authors:
  - "Lucas Fraga (@lfraga)"
  - "James Miranda (@jameswpm)"
description: Segura® PAM Core Ansible collection
license:
- "MIT"
tags:
  - senhasegura
  - segura
  - pam
  - privilege_access_management
repository: "https://github.com/segura-security/ansible-pam-collection"
