fields:
  - id: senhasegura_url
    type: string
    label: Segura® URL
  - id: senhasegura_client_id
    type: string
    label: Segura® A2A Client ID
    secret: true
  - id: senhasegura_client_secret
    type: string
    label: Segura® A2A Client Secret
    secret: true
required:
  - senhasegura_url
  - senhasegura_client_id
  - senhasegura_client_secret  
